# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a265ed20904ee0a97ea69993b1f6a1c00eb02018a4bfe3d6245ee2d93475ef51b12cb7d752cde29549f58f379783ca6b9698c054d686507f22a15e3c7ebdb9

test:
  secret_key_base: 16dfad7f98b2bdb4dd743e7808477f789d75da1efb6e44616794264c1b76d4bdf1ccee8f00f9c9e0b086c8a8e8019070a40d9e9801cc1323850e84da5c3c3ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
